# Generated by Django 5.2.3 on 2025-06-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upgrades', models.IntegerField()),
                ('ap', models.CharField(max_length=20)),
                ('dp', models.IntegerField()),
                ('extra_ap_monsters', models.IntegerField(blank=True, null=True)),
                ('equip_type', models.CharField(choices=[('main_weapon', 'Main Weapon'), ('sub_weapon', 'Sub Weapon'), ('awakening_weapon', 'Awakening Weapon'), ('armor', 'Armor'), ('helmet', 'Helmet'), ('gloves', 'Gloves'), ('shoes', 'Shoes'), ('ring', 'Ring'), ('earring', 'Earring'), ('necklace', 'Necklace'), ('belt', 'Belt')], max_length=32)),
            ],
        ),
    ]
