# Generated by Django 5.2 on 2025-07-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
